### ISSUE TITLE
/bank notsac not working

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#3684]
## 🐛 Bug Report

Every time bank filter not sacrificed is run it returns the interaction failed 

![Screenshot_20220318_161934.jpg](https://user-images.githubusercontent.com/12814878/159042075-b1a12f66-4529-4c92-ad8b-ef77583a2771.jpg)

Still works on +b --notsac

**Comment by 666TURBO** [comment]
> ## 🐛 Bug Report
> 
> Every time bank filter not sacrificed is run it returns the interaction failed 
> 
> ![Screenshot_20220318_161934.jpg](https://user-images.githubusercontent.com/12814878/159042075-b1a12f66-4529-4c92-ad8b-ef77583a2771.jpg)
> 
> Still works on +b --notsac

![Screenshot_20220319-041745_Discord-Beta.png](https://user-images.githubusercontent.com/90441459/159115342-55c48567-8cbc-4888-b43b-4757ba5b7383.png)

**Comment by LuxrayElite** [comment]
I'm talking about the existing choice not sacrificed at the top of the list

![Screenshot_20220319_094449.jpg](https://user-images.githubusercontent.com/12814878/159116152-c512e8b2-ff51-4259-9cfa-eaef0bf2fe36.jpg)

**Comment by LuxrayElite** [comment]
Also tested using --notsac and I get the same error

**Comment by 666TURBO** [comment]
> Also tested using --notsac and I get the same error
> 
> ![Screenshot_20220319_101451.jpg](https://user-images.githubusercontent.com/12814878/159117036-0b5c2454-90ff-4cc5-a3b3-6e7c32d6f5ab.jpg)
> ![Screenshot_20220319_101422.jpg](https://user-images.githubusercontent.com/12814878/159117044-0f4bfef2-0f65-4521-8192-9458fd43de2c.jpg)
> ![Screenshot_20220319_101501.jpg](https://user-images.githubusercontent.com/12814878/159117050-7708c5d1-600d-4e0e-82e3-e142a7b98531.jpg)

it should work now. doing /. I just did it and without adding the —

**Comment by 666TURBO** [comment]
I think he fixed it

**Comment by 666TURBO** [comment]
https://user-images.githubusercontent.com/90441459/159126702-808e59b1-3b28-4391-94df-292da72ed4fc.mp4

**Comment by LuxrayElite** [comment]
Still not working...

https://user-images.githubusercontent.com/12814878/159126962-c619b18b-ac82-47b2-a3ee-61bee4ce1f89.mp4

**Comment by 666TURBO** [comment]
@LuxrayElite are you by chance on birdbot server?

**Comment by 666TURBO** [comment]
> Still not working...
> I'm assuming its due to the size of my sacrificed bank that its timing out before it can do all the comparisons
> https://user-images.githubusercontent.com/12814878/159126962-c619b18b-ac82-47b2-a3ee-61bee4ce1f89.mp4

try this

copy and paste 

`+rp checkbank —fix`

**Comment by LuxrayElite** [comment]
Still not working, and no I'm not in birdbot server

**Comment by 666TURBO** [comment]
> Still not working, and no I'm not in birdbot server

I believe the skyra command is `.servers` on main server in old school not channel

if you don't mind (I'm banned from main lol) could you join birdbot one (it had the green avatar) and we can figure this out

**Comment by 666TURBO** [comment]
![SmartSelect_20220319-102735_Discord-Beta.jpg](https://user-images.githubusercontent.com/90441459/159127324-b0af8583-d856-4e21-bb92-6a924b7f884a.jpg)

**Comment by LuxrayElite** [comment]
Tested with two other users on +lb uniquesac

7th place sean (1316) got an error on performing command
8th place ely josh (1071) was able to perform /bank filter:not sacrificed and get an image returned
image is elyjosh
![image](https://user-images.githubusercontent.com/12814878/159129589-8b876324-a417-4315-bd92-6530abd4af21.png)

**Comment by LuxrayElite** [comment]
Bump.

May also be erroring in the new patreon tools commands as I couldn't run /tools patreon sacrificedbank in testing 

No longer a patreon so can't test
